### ISSUE TITLE
Lack of permissions warning

### ISSUE THREAD

**Issue by Zgrill2** [Zgrill2/ShimmeringReach-FVTT#22]
Would perfer to not display the X for users that do not have delete permissions instead of displaying an error message.
![image](https://user-images.githubusercontent.com/9122236/127167003-da755c70-f282-47f1-9ee1-467e0db5e57a.png)
![image](https://user-images.githubusercontent.com/9122236/127167017-d8aa01e9-3ed0-4154-b94a-e79be9a69ba4.png)

**Comment by Xervous** [comment]
Code updated, resolved
