### ISSUE TITLE
Combat Bugs in Migration Branch

### ISSUE THREAD

**Issue by Zgrill2** [Zgrill2/ShimmeringReach-FVTT#32]
Initial roll
![image (1)](https://user-images.githubusercontent.com/9122236/140628894-a3c07a80-bd30-4c1e-9006-28ce2b026ac7.png)

A few turns later
![image (2)](https://user-images.githubusercontent.com/9122236/140628899-47a74c13-75b3-45aa-a6e9-357907342b73.png)

Bugs:
Skipped Orc with 115 init
Skipped Orc with 113 init
Re-ordered Jon above Rob

_Originally posted by @Zgrill2 in https://github.com/Zgrill2/ShimmeringReach-FVTT/issues/31#issuecomment-962536465_

**Comment by Xervous** [comment]
Resolved
